eeverman/andhow

andhow-usage-examples/src/main/java/howto/force/config/sample/printing/ReallySimpleApp.java, andhow/src/main/java/org/yarnandtail/andhow/AndHow.java, andhow/src/main/java/org/yarnandtail/andhow/Loader.java, andhow/src/main/java/org/yarnandtail/andhow/internal/AndHowCore.java, andhow/src/main/java/org/yarnandtail/andhow/load/EnviromentVariableLoader.java, andhow/src/main/java/org/yarnandtail/andhow/load/FixedValueLoader.java, andhow/src/main/java/org/yarnandtail/andhow/load/JndiLoader.java, andhow/src/main/java/org/yarnandtail/andhow/load/PropertyFileOnClasspathLoader.java, andhow/src/main/java/org/yarnandtail/andhow/load/PropertyFileOnFilesystemLoader.java, andhow/src/main/java/org/yarnandtail/andhow/load/StringArgumentLoader.java, andhow/src/main/java/org/yarnandtail/andhow/load/SystemPropertyLoader.java, andhow/src/test/java/org/yarnandtail/andhow/AndHowTest.java, andhow/src/test/java/org/yarnandtail/andhow/AndHowTestBase.java, andhow/src/test/java/org/yarnandtail/andhow/AndHowUsageExampleTest.java, andhow/src/test/java/org/yarnandtail/andhow/AndHow_AliasInTest.java, andhow/src/test/java/org/yarnandtail/andhow/AndHow_AliasOutTest.java, andhow/src/test/java/org/yarnandtail/andhow/ConstructionDefinitionImmutableTest.java, andhow/src/test/java/org/yarnandtail/andhow/ConstructionDefinitionMutableTest.java, andhow/src/test/java/org/yarnandtail/andhow/NamingStrategyTest.java, andhow/src/test/java/org/yarnandtail/andhow/SimpleParams.java, andhow/src/test/java/org/yarnandtail/andhow/example/restclient/SampleRestClientAppTest.java, andhow/src/test/java/org/yarnandtail/andhow/internal/ValueMapWithContextMutableTest.java, andhow/src/test/java/org/yarnandtail/andhow/load/EnviromentVariableLoaderTest.java, andhow/src/test/java/org/yarnandtail/andhow/load/PropertyFileOnClasspathLoaderAppTest.java, andhow/src/test/java/org/yarnandtail/andhow/load/PropertyFileOnClasspathLoaderUnitTest.java, andhow/src/test/java/org/yarnandtail/andhow/load/PropertyFileOnFilesystemLoaderAppTest.java, andhow/src/test/java/org/yarnandtail/andhow/load/PropertyFileOnFilesystemLoaderUnitTest.java, andhow/src/test/java/org/yarnandtail/andhow/load/StringArgumentLoaderTest.java, andhow/src/test/java/org/yarnandtail/andhow/load/SystemPropertyLoaderTest.java
Also rm the need to pass cmdLineArgs thru various methods during AndHow
construction - the list is just given to the StringArgumentLoader at
construction time.
=> No longer need to add a loader for cmd line args

andhow/src/main/java/org/yarnandtail/andhow/internal/AndHowCore.java, andhow/src/main/java/org/yarnandtail/andhow/util/AndHowUtil.java
Previously using System.out/err, long messages would be interspersed w/
container error messages during failed startups.  By buffering into a
String first, it should be less likely that messages mix.
* rm unused method
fixes #212
=> Sample configuration examples and errors now written as a big string

andhow/src/main/java/org/yarnandtail/andhow/api/Loader.java
After looking at it, it does make sense to keep the Loader.getClassConfig() method around.  Adding better javadocs helps make its purpose clear.
Fixes #165
=> Improved Loader Javadoc

andhow/src/main/java/org/yarnandtail/andhow/internal/AndHowCore.java
This prevents some containers (GlassFish) from messing up the
indentation of the first line by leading it with 'SEVERE:'
Fixes #224
=> Now printing error and samples w/ a leading line separator

andhow/src/main/java/org/yarnandtail/andhow/load/JndiLoader.java
No longer needed after previous change to JNDILoader.
Fixes #223
=> Removed unused String var

andhow/src/main/java/org/yarnandtail/andhow/AndHow.java, andhow/src/main/java/org/yarnandtail/andhow/load/CommandLineArgumentLoader.java
Also found that the cmd line arg loader was not being used as a default loader, which it should have been used for.
=> Renamed the CommandLineArgumentLoader to fix a misspelling.

andhow-annotation-processor/src/main/java/org/yarnandtail/andhow/compile/AndHowCompileProcessor.java, andhow-annotation-processor/src/main/java/org/yarnandtail/andhow/compile/AndHowElementScanner7.java, andhow-system-tests/src/test/java/org/yarnandtail/andhow/AndHowTest.java, andhow/src/main/java/org/yarnandtail/andhow/util/AndHowLog.java, andhow/src/test/java/org/yarnandtail/andhow/util/AndHowLogTest.java
AndHowLogging instances were created as subclasses of java.util.Logger, which caused an undefined state when the Logger constructor was called for a logger name that already existed. Logger handles this by not allowing direct construction - I just uses a static getLogger method that checks to see if the logger exists in the registry hash map. Direct construction had now way to handle this, so the AndHowLogger now uses the same strategy. In the case where the Logger already is registered, a new AndHowLogger wrapper is created for it.
=> AndHowLogging instances were created as subclasses of java.util.Logger

andhow/src/main/java/org/yarnandtail/andhow/api/Loader.java, andhow/src/main/java/org/yarnandtail/andhow/api/LookupLoader.java, andhow/src/main/java/org/yarnandtail/andhow/api/ReadLoader.java, andhow/src/main/java/org/yarnandtail/andhow/load/BaseLoader.java, andhow/src/main/java/org/yarnandtail/andhow/load/EnviromentVariableLoader.java, andhow/src/main/java/org/yarnandtail/andhow/load/FixedValueLoader.java, andhow/src/main/java/org/yarnandtail/andhow/load/JndiLoader.java, andhow/src/main/java/org/yarnandtail/andhow/load/PropertyFileBaseLoader.java, andhow/src/main/java/org/yarnandtail/andhow/load/StringArgumentLoader.java, andhow/src/main/java/org/yarnandtail/andhow/load/SystemPropertyLoader.java
Lookup loaders look in a system which cannot feasibly enumerate all values (JNDI, db connections, etc).
Read loaders are reading from a source where they can.
fixes #263
=> Two new classes of Loaders:  Lookup and Read

andhow-simulated-app-tests/andhow-multimodule-dataprocess/andhow-default-behavior-test/src/test/java/com/map/EarthMapMakerTest.java, andhow-simulated-app-tests/andhow-multimodule-dataprocess/andhow-default-behavior-test/src/test/java/org/dataprocess/ExternalServiceConnectorTest.java, andhow-system-tests/src/test/java/org/yarnandtail/andhow/AndHowTest.java, andhow-system-tests/src/test/java/org/yarnandtail/andhow/AndHowUsageExampleTest.java, andhow-system-tests/src/test/java/org/yarnandtail/andhow/SimpleParams.java, andhow-system-tests/src/test/java/org/yarnandtail/andhow/load/JndiLoaderTest.java, andhow-system-tests/src/test/java/org/yarnandtail/andhow/load/PropertyFileOnClasspathLoaderAppTest.java, andhow-system-tests/src/test/resources/org/yarnandtail/andhow/load/SimpleParamsInvalid.properties, andhow/src/main/java/org/yarnandtail/andhow/api/Loader.java, andhow/src/main/java/org/yarnandtail/andhow/api/PropertyValue.java, andhow/src/main/java/org/yarnandtail/andhow/internal/AndHowCore.java, andhow/src/main/java/org/yarnandtail/andhow/internal/ReportGenerator.java, andhow/src/main/java/org/yarnandtail/andhow/internal/ValueProblem.java, andhow/src/main/java/org/yarnandtail/andhow/load/BaseLoader.java, andhow/src/test/java/org/yarnandtail/andhow/load/StringArgumentLoaderTest.java
* Moved validation from Loader responsibility to AndHowCore, where it is not possible to bypass as it was w/ Loader implementations
* Added several more tests around checking for validation
* To allow ValueProblems to be discovered after loading, the PropertyValue class now has an addProblem() method and is no longer unmodifiable
* AndHowCore has new doPropertyValidations() method where all prop validation happens
* Added JNDI to the app tests and cleaned them up a bit.
=> Better assurance that validation is run on all properties

andhow-annotation-processor-test-harness/pom.xml, andhow-annotation-processor-tests/pom.xml, andhow-annotation-processor/pom.xml, andhow-simulated-app-tests/andhow-multimodule-dataprocess/andhow-default-behavior-dependency/pom.xml, andhow-simulated-app-tests/andhow-multimodule-dataprocess/andhow-default-behavior-test/pom.xml, andhow-system-tests/pom.xml, andhow-test-harness/pom.xml, andhow-usage-examples/complex-example/pom.xml, andhow-usage-examples/force-print-config-example/pom.xml, andhow-usage-examples/pom.xml, andhow-usage-examples/simple-example/pom.xml, andhow/pom.xml, pom.xml
The project compiles in Eclipse as long as it is running on JDK8.
* rm groupId from pom files b/c Eclipse just flags these groups as being duplicates ‘harder’ then in Netbeans, so fixing it here
Fixes #258
=> Cleanup group ids

pom.xml
* Added new Windows profiles w/ params that may be set for the java home
* Added the enforcer plug to support ANDed property activation via a current enough version of Maven
* Now enforcing JDK8 for compiling
=> Added potential patch for Windows to compile w/ JDK8

andhow-core/pom.xml, andhow-test-harness/pom.xml, pom.xml
* GPG no longer run when not releasing
* Javadoc turned off for non-release builds (still runs for main andhow aggregate module)
* rm subproject plugin declarations that were shadowing main project ones
* rm properties that were only used once
=> Cleaned up pom files a bit and rm unneeded build steps

appveyor.yml
Addresses #312.
The instructions for enabling Appveyor on this repo are very similar to those for Travis CI(see comment on #311).
Demonstration that the appveyor process is working, but with the tools.jar error:
https://ci.appveyor.com/project/carlschroedl/andhow/build/8
Here's a demonstration that the appveyor and tools.jar branches produce a successful build when merged onto master:
https://ci.appveyor.com/project/carlschroedl/andhow/build/12
=> Appveyor ci#312

andhow-testing/andhow-annotation-processor-test-harness/pom.xml, andhow-testing/andhow-annotation-processor-tests/pom.xml, andhow-testing/andhow-simulated-app-tests/pom.xml, andhow-testing/andhow-system-tests/pom.xml, andhow-testing/andhow-test-harness/pom.xml
This was an issue for Maven 3.3.9, 3.5.2 seems to have no issue w/ the structure as it was.
(3.3.9 was probably correct to complain)
Fixes #316
=> Added relativePath for test modules to find the master parent pom

andhow-core/src/main/java/org/yarnandtail/andhow/PropertyValue.java, andhow-core/src/test/java/org/yarnandtail/andhow/PropertyValueTest.java
Low impact - was not used
Fixes #327
=> Fixed a bug where the PropertyValue equals always returned false

andhow-annotation-processor/pom.xml, andhow-annotation-processor/src/main/java/org/yarnandtail/andhow/compile/AndHowElementScanner7.java, andhow-core/src/main/java/org/yarnandtail/andhow/StdConfig.java, andhow-core/src/main/java/org/yarnandtail/andhow/api/LocalFileLoader.java, andhow-core/src/main/java/org/yarnandtail/andhow/api/Name.java, andhow-core/src/main/java/org/yarnandtail/andhow/load/std/StdEnvVarLoader.java, andhow-core/src/main/java/org/yarnandtail/andhow/load/std/StdFixedValueLoader.java, andhow-core/src/main/java/org/yarnandtail/andhow/load/std/StdJndiLoader.java, andhow-core/src/main/java/org/yarnandtail/andhow/load/std/StdMainStringArgsLoader.java, andhow-core/src/main/java/org/yarnandtail/andhow/load/std/StdPropFileOnClasspathLoader.java, andhow-core/src/main/java/org/yarnandtail/andhow/load/std/StdPropFileOnFilesystemLoader.java, andhow-core/src/main/java/org/yarnandtail/andhow/load/std/StdSysPropLoader.java, andhow-core/src/main/java/org/yarnandtail/andhow/property/PropertyBuilderBase.java, andhow-core/src/main/java/org/yarnandtail/andhow/service/AbstractPropertyRegistrar.java, andhow-core/src/main/java/org/yarnandtail/andhow/service/PropertyRegistrar.java, andhow-core/src/main/java/org/yarnandtail/andhow/service/PropertyRegistration.java, andhow-core/src/main/java/org/yarnandtail/andhow/service/PropertyRegistrationList.java, andhow-core/src/main/java/org/yarnandtail/andhow/util/NameUtil.java, andhow/pom.xml, pom.xml
fixes #349 
* Added a profile for JDK9+ that uses the new Jigsaw -add-module to include jdk.compile, which includes the functionality previously in the tools.jar
* Update all plugins and several dependencies to versions that support JDK9
* Lots of javadoc cleanup for syntax errors that were tripping up the JDK9 javadocs
=> Cleanup to support building on JDK9 and forward

andhow-core/src/test/java/org/yarnandtail/andhow/valid/DblValidatorTest.java
1. Added a null parameter on the `isValid()` method to all test cases which implements `DblValidator`
2. Added tests for `InvalidSpecificationMessage()`
Since most of the tests are repeated, I was thinking of refactoring some of the lines into a common method. But i'm not sure about the contribution guidelines (IMO unit tests should be as atomic as possible rather than refactoring)
Addresses #392
=> Modifying DblValidator unit tests

andhow-core/src/main/java/org/yarnandtail/andhow/util/TextUtil.java, andhow-core/src/test/java/org/yarnandtail/andhow/util/TextUtilTest.java
Addresses #388 
1. There is a simple logic fix on [#L337](https://github.com/eeverman/andhow/compare/master...shouxian92:increase-textutil-coverage?expand=1#diff-8a18ca74b03a03e942869877a3675e39L337) and [#L359](https://github.com/eeverman/andhow/compare/master...shouxian92:increase-textutil-coverage?expand=1#diff-8a18ca74b03a03e942869877a3675e39L359) of `TextUtil.java`, since my assumption is that the method should return some index only if both input parameters `toBeSearched` and `toBeFound` are present
2. Adds a line to test unicode characters on `escapeXml()`
3. Added a test which checks for strings that goes into "multiline" when it is beyond the string length's limit for `println()` function
=> Increase TextUtil test coverage

andhow/pom.xml, pom.xml
Reduced warnings during build process, specifically around the javadoc generation process by:
- -none: To eliminate all warnings: JDK8+
- additionalparam: <=Maven 2.9 (removed as mvn 3+ used)
- additionalJOption: => Maven 3.0
- doclint: maven-javadoc-plugin 3.0.0+
Also cleaned up the POMs a bit
Fixes issue #444 
Kindly review.
=> Reduced warnings during build process

andhow-core/src/main/java/org/yarnandtail/andhow/valuetype/LocalDateTimeType.java, andhow-core/src/test/java/org/yarnandtail/andhow/AndHowReentrantTest.java
Removing the static get method from ValueType implementations
- `get()` removed from `LocalDateTimeType`
I didn't find any more implementations, but if you can remember any more, @eeverman , please do call them out. 
References #465
=> Removing the static get method from ValueType implementations

andhow-core/src/main/java/org/yarnandtail/andhow/valuetype/BolType.java, andhow-core/src/main/java/org/yarnandtail/andhow/valuetype/DblType.java, andhow-core/src/main/java/org/yarnandtail/andhow/valuetype/FlagType.java, andhow-core/src/main/java/org/yarnandtail/andhow/valuetype/IntType.java, andhow-core/src/main/java/org/yarnandtail/andhow/valuetype/LngType.java, andhow-core/src/main/java/org/yarnandtail/andhow/valuetype/LocalDateTimeType.java, andhow-core/src/main/java/org/yarnandtail/andhow/valuetype/StrType.java
Steps towards adding javadocs & removing the static `get()` method 
- `get()` calls `instance()` internally
- Added (some) javadocs
- Edited a couple of missing javadocs
References:
#466 directly
#455 indirectly
#465 partially
=> Adding Javadocs to org.yarnandtail.andhow.valuetype

andhow-annotation-processor/src/main/java/org/yarnandtail/andhow/compile/AndHowCompileProcessor.java, pom.xml
Also update the pom to:
* specify 1.8 as the source and target
* Specify a Java version as 1.8 to 15
* Specify a Maven version 3.5 up to 4.0
Fixes #492
=> AnnotationProcessor now reports it supports all JDK versions

andhow-annotation-processor/src/main/java/org/yarnandtail/andhow/compile/CompileUtil.java, andhow-annotation-processor/src/main/java/org/yarnandtail/andhow/compile/PropertyRegistrarClassGenerator.java, andhow-annotation-processor/src/main/resources/org/yarnandtail/andhow/compile/PropertyRegistrarClassGenerator_Template.txt, andhow-annotation-processor/src/test/java/org/yarnandtail/andhow/compile/CompileUtilTest.java, andhow-annotation-processor/src/test/java/org/yarnandtail/andhow/compile/PropertyRegistrarClassGeneratorTest.java
Fixes Issue #491 
Actually, its doesn't really fix the issue (there are still warnings in IntelliJ), but it tries the intended approach and the Generated annotation should be used anyway.
It sounds like the warnings are really an IntelliJ bug:
https://youtrack.jetbrains.com/issue/IDEA-159676
=> Now using the Generated annotation on generated files

andhow-annotation-processor/pom.xml, andhow-annotation-processor/src/test/java/org/yarnandtail/andhow/compile/AndHowCompileProcessor_PropertyTest.java, andhow-core/pom.xml, andhow-testing/andhow-annotation-processor-test-harness/pom.xml, andhow-testing/andhow-annotation-processor-test-harness/src/main/java/org/yarnandtail/compile/AndHowCompileProcessorTestBase.java, andhow-testing/andhow-annotation-processor-tests/pom.xml, andhow-testing/andhow-simulated-app-tests/andhow-multimodule-dataprocess/pom.xml, andhow-testing/andhow-system-tests/pom.xml, codecov.yml, pom.xml
* Moved the AndHowCompileProcessorTestBase to the test harness module
* cleaned up junit related dependency declaration in pom files
=> Exclude annotation-processor-test-harness from the codecov report

andhow-core/src/main/java/org/yarnandtail/andhow/AndHow.java, andhow-core/src/main/java/org/yarnandtail/andhow/AndHowConfiguration.java, andhow-core/src/main/java/org/yarnandtail/andhow/BaseConfig.java, andhow-core/src/main/java/org/yarnandtail/andhow/util/AndHowUtil.java, andhow-core/src/test/java/org/yarnandtail/andhow/AndHowReentrantTest.java, andhow-core/src/test/java/org/yarnandtail/andhow/AndHowTest.java, andhow-core/src/test/java/org/yarnandtail/andhow/AndHowTestUtil.java, andhow-core/src/test/java/org/yarnandtail/andhow/AndHowUsageExampleTest.java, andhow-core/src/test/java/org/yarnandtail/andhow/AndHow_AliasInTest.java, andhow-core/src/test/java/org/yarnandtail/andhow/AndHow_AliasOutTest.java, andhow-core/src/test/java/org/yarnandtail/andhow/StdConfigSimulatedAppTest.java, andhow-core/src/test/java/org/yarnandtail/andhow/load/PropFileOnClasspathLoaderAppTest.java, andhow-core/src/test/java/org/yarnandtail/andhow/load/PropFileOnFilesystemLoaderAppTest.java, andhow-core/src/test/java/org/yarnandtail/andhow/load/std/StdJndiLoaderTest.java, andhow-core/src/test/java/org/yarnandtail/andhow/property/PropertyTestBase.java, andhow-testing/andhow-integration-test/src/test/java/org/yarnandtail/andhow/AndHowTest.java, andhow-testing/andhow-test-harness/src/main/java/org/yarnandtail/andhow/AndHowNonProductionUtil.java
* Add AndHow.setConfig(config)
* Lots of test cleanup for fewer warnings
* Cleaner tests using assertThrows instead of try/catch in a few places
=> Deprecated AndHow.instance(config) and AndHowConfig.build()

andhow-core/pom.xml, andhow-testing/andhow-simulated-app-tests/andhow-multimodule-dataprocess/pom.xml
Fixes #546
* Replace deprecated maven expressions `${groupId}`, `${version}` with `${project.groupId}` and `${project.version}` 
* [+] Your pull request is to the *_main_* branch
* [+] Your code is up to date with the latest code from the *_main_*
* [+] You followed the guidelines in our [Developer Guide](https://sites.google.com/view/andhow/developer)?
* [+] Your code does not decrease test coverage (maybe it improves coverage!!)
* [+] If this is related to an issue, please include a link to the issue with the 'Fixes #XXX' syntax.
=> Replace deprecated maven expressions

andhow-core/src/main/java/org/yarnandtail/andhow/AndHowConfiguration.java, andhow-core/src/main/java/org/yarnandtail/andhow/StdConfig.java, andhow-core/src/test/java/org/yarnandtail/andhow/StdConfigGetterAndSetterTest.java
Fixes #509
* Update setter to remove previously set arguments.
* Cover with test.
* Update javadoc.
* [+] Your pull request is to the *_main_* branch
* [+] Your code is up to date with the latest code from the *_main_*
* [+] You followed the guidelines in our [Developer Guide](https://sites.google.com/view/andhow/developer)?
* [+] Your code does not decrease test coverage (maybe it improves coverage!!)
* [+] If this is related to an issue, please include a link to the issue with the 'Fixes #XXX' syntax.
=> Fix StdConfig#setCmdLineArgs (#509)

andhow-core/src/main/java/org/yarnandtail/andhow/AndHow.java, andhow-core/src/main/java/org/yarnandtail/andhow/AndHowConfiguration.java, andhow-core/src/main/java/org/yarnandtail/andhow/AndHowTestInit.java, andhow-core/src/main/java/org/yarnandtail/andhow/StdConfig.java, andhow-core/src/main/java/org/yarnandtail/andhow/load/std/StdPropFileOnClasspathLoader.java, andhow-junit5-extensions/src/main/java/org/yarnandtail/andhow/junit5/EnableJndiForThisTestClass.java, andhow-junit5-extensions/src/main/java/org/yarnandtail/andhow/junit5/EnableJndiForThisTestMethod.java, andhow-junit5-extensions/src/main/java/org/yarnandtail/andhow/junit5/KillAndHowBeforeAllTests.java, andhow-junit5-extensions/src/main/java/org/yarnandtail/andhow/junit5/KillAndHowBeforeEachTest.java, andhow-junit5-extensions/src/main/java/org/yarnandtail/andhow/junit5/KillAndHowBeforeThisTest.java, andhow-junit5-extensions/src/main/java/org/yarnandtail/andhow/junit5/RestoreSysPropsAfterEachTest.java, andhow-junit5-extensions/src/main/java/org/yarnandtail/andhow/junit5/RestoreSysPropsAfterThisTest.java, andhow-testing/andhow-simulated-app-tests/example-app-1/src/main/java/com/bigcorp/Calculator.java, andhow-testing/andhow-simulated-app-tests/example-app-1/src/test/java/com/bigcorp/CalculatorDefaultTest.java, andhow-testing/andhow-simulated-app-tests/example-app-1/src/test/java/com/bigcorp/CalculatorDoubleConfigTest.java, andhow-testing/andhow-simulated-app-tests/example-app-2/src/main/java/com/bigcorp/Checker.java, andhow-testing/andhow-simulated-app-tests/example-app-2/src/test/java/com/bigcorp/CheckerDefaultAndMainArgsTest.java, andhow-testing/andhow-simulated-app-tests/example-app-2/src/test/java/com/bigcorp/CheckerFixedValuesTest.java, andhow-testing/andhow-test-harness/src/main/java/org/yarnandtail/andhow/AndHowTestBase.java
Fixes #545
* Fixe Javadocs annotations
```
@Code,@CODE => @code
@See        => @see
@depricated => @deprecated
```
* Fixe Javadocs with special charracters inside `<pre>{@code}` tag
=> Issue 545 fix code annotation

andhow-core/src/main/java/org/yarnandtail/andhow/api/ExportGroup.java, andhow-core/src/main/java/org/yarnandtail/andhow/api/Exporter.java, andhow-core/src/main/java/org/yarnandtail/andhow/export/BaseExporter.java, andhow-core/src/main/java/org/yarnandtail/andhow/internal/AndHowCore.java
* Removed dead code that was never used related to bulk exports
* Deprecated method has a default no-op implementation so subclasses don't need to implement it
* Improve javadocs
=> Deprecated & remove bulk export partial implementation

andhow-core/src/main/java/org/yarnandtail/andhow/load/KeyValuePairLoader.java, andhow-core/src/test/java/org/yarnandtail/andhow/load/KeyValuePairLoaderTest.java
Fixes #552
* Deprecate KeyValuePairLoader.setKeyValuePairs(String... keyValuePairs)
=> Deprecate KeyValuePairLoader.setKeyValuePairs(String... keyValuePairs)

andhow-core/src/main/java/org/yarnandtail/andhow/load/FixedValueLoader.java, andhow-core/src/test/java/org/yarnandtail/andhow/load/FixedValueLoaderTest.java
Fixes #553 
* Deprecate FixedValueLoader#setPropertyValues(PropertyValue... values)
* Change javadoc
* Add unit test.
=> Deprecate FixedValueLoader#setPropertyValues(PropertyValue... values)

andhow-annotation-processor/pom.xml, andhow-core/pom.xml, andhow-testing/andhow-annotation-processor-test-harness/pom.xml, andhow-testing/andhow-annotation-processor-tests/pom.xml, andhow-testing/andhow-simulated-app-tests/andhow-multimodule-dataprocess/andhow-default-behavior-dep1/pom.xml, andhow-testing/andhow-simulated-app-tests/andhow-multimodule-dataprocess/andhow-default-behavior-dep2/pom.xml, andhow-testing/andhow-simulated-app-tests/andhow-multimodule-dataprocess/andhow-default-behavior-test/pom.xml, andhow-testing/andhow-simulated-app-tests/andhow-multimodule-dataprocess/pom.xml, andhow-testing/andhow-simulated-app-tests/pom.xml, andhow-testing/andhow-system-tests/pom.xml, andhow-testing/andhow-test-harness/pom.xml, andhow/pom.xml, pom.xml
=> Issue592 packaging error

andhow-core/src/main/java/org/yarnandtail/andhow/api/NamingStrategy.java, andhow-core/src/main/java/org/yarnandtail/andhow/load/std/StdJndiLoader.java
Fixes #526
* Rename NamingStrategy#isUriNameDistict
* Remove redundant access modifier
=> Fix spelling mistake

andhow-core/src/main/java/org/yarnandtail/andhow/Options.java, andhow-core/src/main/java/org/yarnandtail/andhow/property/StrProp.java, andhow-core/src/test/java/org/yarnandtail/andhow/AndHowTest.java, andhow-core/src/test/java/org/yarnandtail/andhow/SimpleParams.java, andhow-core/src/test/java/org/yarnandtail/andhow/StdConfigSimulatedAppTest.java, andhow-core/src/test/java/org/yarnandtail/andhow/internal/StaticPropertyConfigurationImmutableTest.java, andhow-core/src/test/java/org/yarnandtail/andhow/internal/StaticPropertyConfigurationMutableTest.java, andhow-core/src/test/java/org/yarnandtail/andhow/load/BaseForLoaderTests.java, andhow-core/src/test/java/org/yarnandtail/andhow/load/std/StdJndiLoaderTest.java, andhow-core/src/test/java/org/yarnandtail/andhow/property/PropertyBaseTest.java, andhow-core/src/test/java/org/yarnandtail/andhow/property/StrPropTest.java, andhow-core/src/test/java/org/yarnandtail/andhow/sample/JndiLoaderSamplePrinterTest.java, andhow-core/src/test/java/org/yarnandtail/andhow/sample/PropFileLoaderSamplePrinterTest.java, andhow-testing/andhow-simulated-app-tests/andhow-multimodule-dataprocess/andhow-default-behavior-dep1/src/main/java/com/dep1/EarthMapMaker.java, andhow-testing/andhow-simulated-app-tests/andhow-multimodule-dataprocess/andhow-default-behavior-dep2/src/main/java/com/dep2/MarsMapMaker.java, andhow-testing/andhow-simulated-app-tests/andhow-multimodule-dataprocess/andhow-default-behavior-test/src/main/java/org/dataprocess/ExternalServiceConnector.java, andhow-testing/andhow-simulated-app-tests/example-app-1/src/main/java/com/bigcorp/Calculator.java, andhow-testing/andhow-simulated-app-tests/example-app-2/src/main/java/com/bigcorp/AppInitiation.java, andhow-testing/andhow-simulated-app-tests/example-app-2/src/main/java/com/bigcorp/Checker.java, andhow-testing/andhow-simulated-app-tests/example-app-3/src/main/java/com/bigcorp/HibernateInit.java
Fixes #587 
Shorted Property builder:
* Update StrProp.StrBuilder methods to the new names.
* Mark old methods as deprecated, delegate to new methods.
* Add javadoc for deprecated methods with references to new methods.
* Update all usages to the new method names.
=> Issue587 shorted StrProp builder

andhow-core/src/main/java/org/yarnandtail/andhow/property/BigDecProp.java, andhow-core/src/main/java/org/yarnandtail/andhow/property/DblProp.java, andhow-core/src/main/java/org/yarnandtail/andhow/property/IntProp.java, andhow-core/src/main/java/org/yarnandtail/andhow/property/LngProp.java, andhow-core/src/test/java/org/yarnandtail/andhow/AndHowUsageExampleTest.java, andhow-core/src/test/java/org/yarnandtail/andhow/SimpleParams.java, andhow-core/src/test/java/org/yarnandtail/andhow/StdConfigSimulatedAppTest.java, andhow-core/src/test/java/org/yarnandtail/andhow/load/std/StdJndiLoaderTest.java, andhow-testing/andhow-simulated-app-tests/example-app-2/src/main/java/com/bigcorp/Checker.java, andhow-testing/andhow-simulated-app-tests/example-app-3/src/main/java/com/bigcorp/HibernateInit.java
Fixes #608 
Shorted Property builder:
* Update numeric builder methods to the new names.
* Mark old methods as deprecated, delegate to new methods.
* Add javadoc for deprecated methods with references to new methods.
* Update all usages to the new method names.
=> Shorted Property builder methods for numeric Properties

andhow-core/src/main/java/org/yarnandtail/andhow/Options.java, andhow-core/src/main/java/org/yarnandtail/andhow/load/std/StdJndiLoader.java, andhow-core/src/main/java/org/yarnandtail/andhow/property/PropertyBuilderBase.java, andhow-core/src/test/java/org/yarnandtail/andhow/AndHowTest.java, andhow-core/src/test/java/org/yarnandtail/andhow/AndHowUsageExampleTest.java, andhow-core/src/test/java/org/yarnandtail/andhow/AndHow_AliasInTest.java, andhow-core/src/test/java/org/yarnandtail/andhow/AndHow_AliasOutTest.java, andhow-core/src/test/java/org/yarnandtail/andhow/StdConfigSimulatedAppTest.java, andhow-core/src/test/java/org/yarnandtail/andhow/load/PropFileOnClasspathLoaderUnitTest.java, andhow-core/src/test/java/org/yarnandtail/andhow/load/PropFileOnFilesystemLoaderUnitTest.java, andhow-core/src/test/java/org/yarnandtail/andhow/property/BigDecPropTest.java, andhow-core/src/test/java/org/yarnandtail/andhow/property/BolPropTest.java, andhow-core/src/test/java/org/yarnandtail/andhow/property/PropertyBaseTest.java, andhow-core/src/test/java/org/yarnandtail/andhow/property/PropertyBuilderBaseTest.java, andhow-core/src/test/java/org/yarnandtail/andhow/property/PropertyTestBase.java, andhow-core/src/test/java/org/yarnandtail/andhow/property/StrPropTest.java, andhow-core/src/test/java/org/yarnandtail/andhow/sample/JndiLoaderSamplePrinterTest.java, andhow-core/src/test/java/org/yarnandtail/andhow/sample/PropFileLoaderSamplePrinterTest.java, andhow-testing/andhow-simulated-app-tests/andhow-multimodule-dataprocess/andhow-default-behavior-dep1/src/main/java/com/dep1/EarthMapMaker.java, andhow-testing/andhow-simulated-app-tests/andhow-multimodule-dataprocess/andhow-default-behavior-dep2/src/main/java/com/dep2/MarsMapMaker.java, andhow-testing/andhow-simulated-app-tests/andhow-multimodule-dataprocess/andhow-default-behavior-test/src/main/java/org/dataprocess/ExternalServiceConnector.java, andhow-testing/andhow-simulated-app-tests/example-app-1/src/main/java/com/bigcorp/Calculator.java, andhow-testing/andhow-simulated-app-tests/example-app-2/src/main/java/com/bigcorp/Checker.java, andhow-testing/andhow-simulated-app-tests/example-app-3/src/main/java/com/bigcorp/HibernateInit.java
Fixes #609 
* Create new method `notNull` in the PropertyBuilderBase.
* Mark old method `mustBeNonNull()` as deprecated and reuse new method.
* All usages in the project updated to the new method.
=> Shorten PropertyBuilderBase builder method name
