eeverman/andhow

src/main/java/yarnandtail/andhow/AppConfig.java, src/main/java/yarnandtail/andhow/ConfigPoint.java, src/main/java/yarnandtail/andhow/LoaderValues.java, src/main/java/yarnandtail/andhow/appconfig/AppConfigStructuredValuesBase.java, src/main/java/yarnandtail/andhow/appconfig/AppConfigValuesUnmodifiable.java, src/main/java/yarnandtail/andhow/point/ConfigPointBase.java, src/main/java/yarnandtail/andhow/point/FlagConfigPoint.java, src/main/java/yarnandtail/andhow/point/FlagPointBuilder.java, src/main/java/yarnandtail/andhow/point/IntConfigPoint.java, src/main/java/yarnandtail/andhow/point/IntPointBuilder.java, src/main/java/yarnandtail/andhow/point/StringConfigPoint.java, src/main/java/yarnandtail/andhow/point/StringPointBuilder.java, src/test/java/yarnandtail/andhow/name/BasicNamingStrategyTest.java
Accidental merge before commit on this branch before
=> actual code for this branch

src/main/java/yarnandtail/andhow/ConfigGroupDescription.java, src/main/java/yarnandtail/andhow/ReportGenerator.java, src/main/java/yarnandtail/andhow/load/PropFileLoader.java
* Added group descriptions to sample output
* Cleaner problem and sample reports
* Fixed bug in group annotations
=> PropFileLoader now has default

andhow/src/main/java/yarnandtail/andhow/AppFatalException.java, andhow/src/main/java/yarnandtail/andhow/ConstructionProblem.java, andhow/src/main/java/yarnandtail/andhow/PropertyValue.java, andhow/src/main/java/yarnandtail/andhow/PropertyValueProblem.java, andhow/src/main/java/yarnandtail/andhow/ReportGenerator.java, andhow/src/main/java/yarnandtail/andhow/internal/AndHowUtil.java, andhow/src/main/java/yarnandtail/andhow/internal/RuntimeDefinition.java, andhow/src/main/java/yarnandtail/andhow/load/BaseLoader.java, andhow/src/test/java/yarnandtail/andhow/AndHowTest.java, andhow/src/test/java/yarnandtail/andhow/RuntimeDefinitionTest.java, andhow/src/test/java/yarnandtail/andhow/example/restclient/SampleRestClientAppTest.java
For consistency w/ rename of ConfigPoint to Property
=> Found some addition renamings

andhow/src/main/java/yarnandtail/andhow/ConfigSamplePrinter.java, andhow/src/main/java/yarnandtail/andhow/load/PropFileLoader.java
Add a validation to the PropFileLoader
=> more output tweaks & fixes

andhow/src/main/java/yarnandtail/andhow/AndHow.java, andhow/src/main/java/yarnandtail/andhow/AppFatalException.java, andhow/src/test/java/yarnandtail/andhow/AndHow_DefaultAndForceValueTest.java
=> Improved handling of error conditions for forced and default values

andhow/src/main/java/yarnandtail/andhow/load/KVP.java, andhow/src/test/java/yarnandtail/andhow/load/KVPTest.java
=> fixed - multiple delimiters now allowed

andhow/src/main/java/yarnandtail/andhow/LoaderProblem.java, andhow/src/main/java/yarnandtail/andhow/load/BaseLoader.java, andhow/src/test/java/yarnandtail/andhow/load/CmdLineLoaderTest.java, andhow/src/test/java/yarnandtail/andhow/load/PropFileLoaderTest.java, andhow/src/test/resources/yarnandtail/andhow/load/SimpleParams6.properties
* Added testing
Fixes issue #21
=> Loaders now complain if they find an unrecognized property

andhow-usage-examples/pom.xml, andhow/pom.xml, pom.xml
Updated license in pom and small fixes
=> Checkin for 0.2.1 Release

README.md, andhow/src/main/java/yarnandtail/andhow/NamingStrategy.java, andhow/src/main/java/yarnandtail/andhow/internal/RuntimeDefinition.java, andhow/src/main/java/yarnandtail/andhow/load/JndiLoader.java, andhow/src/test/java/yarnandtail/andhow/NamingStrategyTest.java, andhow/src/test/java/yarnandtail/andhow/load/JndiLoaderTest.java
* Improvements to readme text
* New naming strategy static method for creating URI names
=> Add support for URI based JNDI names

andhow/src/main/java/yarnandtail/andhow/LoaderProblem.java, andhow/src/main/java/yarnandtail/andhow/ParsingException.java, andhow/src/main/java/yarnandtail/andhow/ValueProblem.java, andhow/src/main/java/yarnandtail/andhow/ValueType.java, andhow/src/main/java/yarnandtail/andhow/load/BaseLoader.java, andhow/src/main/java/yarnandtail/andhow/load/JndiLoader.java, andhow/src/test/java/yarnandtail/andhow/example/restclient/SampleRestClientAppTest.java, andhow/src/test/java/yarnandtail/andhow/load/JndiLoaderTest.java
* rm extra unused field in ParsingException
* mv StringConversionproblem from ValueProblem to LoaderProblem for
better consistency.  This type of error results in not being able to
create a Property, so belongs as a Loader problem.
=> Added tests for non-happy path JndiLoader cases

andhow/src/main/java/yarnandtail/andhow/ValueType.java, andhow/src/main/java/yarnandtail/andhow/load/BaseLoader.java, andhow/src/main/java/yarnandtail/andhow/valuetype/BaseValueType.java, andhow/src/main/java/yarnandtail/andhow/valuetype/FlagType.java, andhow/src/main/java/yarnandtail/andhow/valuetype/IntType.java, andhow/src/main/java/yarnandtail/andhow/valuetype/StringType.java
=> Renamed the parse methods

andhow/src/main/java/yarnandtail/andhow/internal/ConstructionDefinitionMutable.java, andhow/src/test/java/yarnandtail/andhow/AndHow_AliasInTest.java, andhow/src/test/java/yarnandtail/andhow/AndHow_AliasOutTest.java
Fixes #121 
* Added tests for duplicate in names
* Fixed a bug where no Problem was recorded for dup out names
* Added tests for out names
=> Added test and fix for detecting duplicate alias

andhow/src/main/java/yarnandtail/andhow/NamingStrategy.java, andhow/src/main/java/yarnandtail/andhow/load/JndiLoader.java, andhow/src/main/java/yarnandtail/andhow/sample/BaseSamplePrinter.java, andhow/src/main/java/yarnandtail/andhow/sample/JndiLoaderSamplePrinter.java, andhow/src/main/java/yarnandtail/andhow/sample/PropFileLoaderSamplePrinter.java, andhow/src/test/java/yarnandtail/andhow/AndHow_AliasInTest.java, andhow/src/test/java/yarnandtail/andhow/NamingStrategyTest.java, andhow/src/test/java/yarnandtail/andhow/SimpleParams.java, andhow/src/test/java/yarnandtail/andhow/example/restclient/SampleRestClientGroup.java, andhow/src/test/java/yarnandtail/andhow/load/JndiLoaderTest.java
NamingStrategy moved some static methods to instance.
fixes #139
=> JNDI samples now include URI style aliases

andhow-usage-examples/pom.xml, andhow/pom.xml, pom.xml
=> Lots of pom updates to Sonotype requirements

andhow/src/main/java/org/yarnandtail/andhow/AndHow.java, andhow/src/main/java/org/yarnandtail/andhow/PropertyValue.java, andhow/src/main/java/org/yarnandtail/andhow/internal/AndHowCore.java, andhow/src/main/java/org/yarnandtail/andhow/name/CaseInsensitiveNaming.java, andhow/src/test/java/org/yarnandtail/andhow/AndHowTest.java, andhow/src/test/java/org/yarnandtail/andhow/AndHow_AliasInTest.java, andhow/src/test/java/org/yarnandtail/andhow/AndHow_AliasOutTest.java, andhow/src/test/java/org/yarnandtail/andhow/ConstructionDefinitionImmutableTest.java, andhow/src/test/java/org/yarnandtail/andhow/ConstructionDefinitionMutableTest.java, andhow/src/test/java/org/yarnandtail/andhow/NamingStrategyTest.java, andhow/src/test/java/org/yarnandtail/andhow/load/EnviromentVariableLoaderTest.java, andhow/src/test/java/org/yarnandtail/andhow/load/JndiLoaderTest.java, andhow/src/test/java/org/yarnandtail/andhow/load/KVPTest.java, andhow/src/test/java/org/yarnandtail/andhow/load/PropertyFileOnClasspathLoaderAppTest.java, andhow/src/test/java/org/yarnandtail/andhow/load/PropertyFileOnClasspathLoaderUnitTest.java, andhow/src/test/java/org/yarnandtail/andhow/load/PropertyFileOnFilesystemLoaderAppTest.java, andhow/src/test/java/org/yarnandtail/andhow/load/PropertyFileOnFilesystemLoaderUnitTest.java, andhow/src/test/java/org/yarnandtail/andhow/load/StringArgumentLoaderTest.java, andhow/src/test/java/org/yarnandtail/andhow/load/SystemPropertyLoaderTest.java, andhow/src/test/java/org/yarnandtail/andhow/name/CaseInsensitiveNamingTest.java
Cleaned up imports
Updated test names
=> Renamed the BasicNamingStrategy to CaseInsensitiveNaming.

andhow/src/main/java/org/yarnandtail/andhow/AndHow.java, andhow/src/main/java/org/yarnandtail/andhow/EffectiveName.java, andhow/src/main/java/org/yarnandtail/andhow/GroupExport.java, andhow/src/main/java/org/yarnandtail/andhow/GroupExports.java, andhow/src/main/java/org/yarnandtail/andhow/Name.java, andhow/src/main/java/org/yarnandtail/andhow/PropertyValue.java, andhow/src/main/java/org/yarnandtail/andhow/load/StringArgumentLoader.java, andhow/src/main/java/org/yarnandtail/andhow/util/TextUtil.java, andhow/src/test/java/org/yarnandtail/andhow/AndHowTest.java, andhow/src/test/java/org/yarnandtail/andhow/AndHowUsageExampleTest.java, andhow/src/test/java/org/yarnandtail/andhow/NameTest.java, andhow/src/test/java/org/yarnandtail/andhow/example/restclient/SampleRestClientAppTest.java, andhow/src/test/java/org/yarnandtail/andhow/load/KVPTest.java, andhow/src/test/java/org/yarnandtail/andhow/load/StringArgumentLoaderTest.java, andhow/src/test/java/org/yarnandtail/andhow/util/TextUtilTest.java
removed most incoming dependencies
=> Packing cleanup of the root package

pom.xml
now using only the remote profile for deploy and release
=> removed release profile

andhow-usage-examples/pom.xml, andhow/pom.xml, pom.xml
This branch has the (ultimately) successful changes to the pom to do the 0.3.0 release
=> Exp 0.3.0 release branch

andhow/src/main/java/org/yarnandtail/andhow/internal/ConstructionProblem.java
=> Improved error msg for unregistered loader prop

andhow/src/main/java/org/yarnandtail/andhow/internal/ConstructionProblem.java, andhow/src/main/java/org/yarnandtail/andhow/util/AndHowUtil.java, andhow/src/test/java/org/yarnandtail/andhow/load/PropertyFileOnClasspathLoaderAppTest.java
=> Added new ConstructionProblem type

andhow-usage-examples/pom.xml, andhow/pom.xml, pom.xml
This was actually a release, but I did not realize I was on a branch at the time.  Should still work ok.
=> Begin 0.4.0-snapshot

andhow-usage-examples/src/main/java/org/dataprocess/SampleAppConfiguration.java, andhow-usage-examples/src/main/java/org/simple/SimpleSample.java, andhow/src/main/java/org/yarnandtail/andhow/api/Property.java, andhow/src/main/java/org/yarnandtail/andhow/api/SamplePrinter.java, andhow/src/main/java/org/yarnandtail/andhow/internal/AndHowCore.java, andhow/src/main/java/org/yarnandtail/andhow/internal/RequirementProblem.java, andhow/src/main/java/org/yarnandtail/andhow/load/JndiLoader.java, andhow/src/main/java/org/yarnandtail/andhow/property/DblProp.java, andhow/src/main/java/org/yarnandtail/andhow/property/FlagProp.java, andhow/src/main/java/org/yarnandtail/andhow/property/IntProp.java, andhow/src/main/java/org/yarnandtail/andhow/property/LngProp.java, andhow/src/main/java/org/yarnandtail/andhow/property/LocalDateTimeProp.java, andhow/src/main/java/org/yarnandtail/andhow/property/PropertyBase.java, andhow/src/main/java/org/yarnandtail/andhow/property/PropertyBuilderBase.java, andhow/src/main/java/org/yarnandtail/andhow/property/StrProp.java, andhow/src/main/java/org/yarnandtail/andhow/sample/BaseSamplePrinter.java, andhow/src/test/java/org/yarnandtail/andhow/AndHowTest.java, andhow/src/test/java/org/yarnandtail/andhow/AndHowUsageExampleTest.java, andhow/src/test/java/org/yarnandtail/andhow/AndHow_AliasInTest.java, andhow/src/test/java/org/yarnandtail/andhow/AndHow_AliasOutTest.java, andhow/src/test/java/org/yarnandtail/andhow/example/restclient/SampleRestClientGroup.java, andhow/src/test/java/org/yarnandtail/andhow/load/PropertyFileOnClasspathLoaderUnitTest.java, andhow/src/test/java/org/yarnandtail/andhow/load/PropertyFileOnFilesystemLoaderUnitTest.java, andhow/src/test/java/org/yarnandtail/andhow/property/PropertyTestBase.java, andhow/src/test/java/org/yarnandtail/andhow/property/StrPropTest.java
This touches a lot of code.
Fixes #219
=> Renaming required() to nonNull()

andhow/src/main/java/org/yarnandtail/andhow/api/Property.java, andhow/src/main/java/org/yarnandtail/andhow/property/DblProp.java, andhow/src/main/java/org/yarnandtail/andhow/property/FlagProp.java, andhow/src/main/java/org/yarnandtail/andhow/property/IntProp.java, andhow/src/main/java/org/yarnandtail/andhow/property/LngProp.java, andhow/src/main/java/org/yarnandtail/andhow/property/LocalDateTimeProp.java, andhow/src/main/java/org/yarnandtail/andhow/property/PropertyBase.java, andhow/src/main/java/org/yarnandtail/andhow/property/PropertyBuilderBase.java, andhow/src/main/java/org/yarnandtail/andhow/property/StrProp.java, andhow/src/main/java/org/yarnandtail/andhow/sample/BaseSamplePrinter.java, andhow/src/test/java/org/yarnandtail/andhow/property/StrPropTest.java
=> Renamed Property's getShortDescription to getDescription

andhow/src/main/java/org/yarnandtail/andhow/api/ValueType.java, andhow/src/main/java/org/yarnandtail/andhow/property/FlagProp.java, andhow/src/main/java/org/yarnandtail/andhow/property/PropertyBuilderBase.java, andhow/src/test/java/org/yarnandtail/andhow/AndHowTest.java, andhow/src/test/java/org/yarnandtail/andhow/SimpleParams.java, andhow/src/test/java/org/yarnandtail/andhow/load/EnviromentVariableLoaderTest.java, andhow/src/test/java/org/yarnandtail/andhow/load/SystemPropertyLoaderTest.java
This is a behavioral change:  FlagProp will now never return null
=> FlagProp now uses a default value instead of a custom getValue method

andhow-system-tests/src/test/java/org/yarnandtail/andhow/example/restclient/SampleRestClientAppTest.java, andhow/src/main/java/org/yarnandtail/andhow/AndHow.java, andhow/src/main/java/org/yarnandtail/andhow/Options.java, andhow/src/main/java/org/yarnandtail/andhow/api/AppFatalException.java, andhow/src/main/java/org/yarnandtail/andhow/api/SamplePrinter.java, andhow/src/main/java/org/yarnandtail/andhow/internal/AndHowCore.java, andhow/src/main/java/org/yarnandtail/andhow/internal/ReportGenerator.java, andhow/src/main/java/org/yarnandtail/andhow/sample/JndiLoaderSamplePrinter.java, andhow/src/main/java/org/yarnandtail/andhow/sample/PropFileLoaderSamplePrinter.java, andhow/src/main/java/org/yarnandtail/andhow/util/IOUtil.java, andhow/src/test/java/org/yarnandtail/andhow/util/IOUtilTest.java
=> sample printing now goes to a temp directory

andhow-system-tests/src/test/java/org/yarnandtail/andhow/AndHow_AliasInTest.java, andhow-system-tests/src/test/java/org/yarnandtail/andhow/example/restclient/SampleRestClientAppTest.java, andhow-system-tests/src/test/java/org/yarnandtail/andhow/load/JndiLoaderTest.java, andhow-test-harness/src/main/java/org/yarnandtail/andhow/AndHowTestBase.java, andhow/src/main/java/org/yarnandtail/andhow/AndHow.java
=> JNDI Loader now added as a default loader

andhow/src/main/java/org/yarnandtail/andhow/internal/ReportGenerator.java, andhow/src/main/java/org/yarnandtail/andhow/util/AndHowLog.java
Also improvement logged text for the ReportGenerator
=> AndHowLog was dual logging because it was delegating to the parent log

andhow-test-harness/src/main/java/org/yarnandtail/andhow/AndHowNonProduction.java, andhow/src/main/java/org/yarnandtail/andhow/AndHow.java
* Improved docs
* rm unused / hard to implement method
Fixed Issue #273
=> Fixed an issue where cmd line loader could get doubled up

andhow-core/src/main/java/org/yarnandtail/andhow/AndHow.java, andhow-core/src/main/java/org/yarnandtail/andhow/internal/AndHowCore.java, andhow-core/src/main/java/org/yarnandtail/andhow/internal/ReportGenerator.java
* A bit of import cleanup
Fixes #284
=> Fixed the ReportGenerator to not append for sample files

README.md, andhow-annotation-processor/src/main/java/org/yarnandtail/andhow/compile/AndHowCompileProcessor.java, andhow-annotation-processor/src/main/resources/org/yarnandtail/andhow/compile/PropertyRegistrarClassGenerator_Template.txt
* Updated the readme to clarify Java9 support
* General cleanup
Fixes #298
=> Rm Generated annotation from gen classes b/c it is not part of the Java9 runtime

andhow-core/src/main/java/org/yarnandtail/andhow/StdConfig.java, andhow-core/src/main/java/org/yarnandtail/andhow/sample/BaseSamplePrinter.java, andhow-test-harness/src/main/java/org/yarnandtail/andhow/NonProductionConfig.java, pom.xml
* quiet'ed excess javadoc logging
* Improved sample generation format
* rm unused imports
=> Minor cleanup

pom.xml
Addresses #257.
Added fix from maven documentation.
https://maven.apache.org/general.html#tools-jar-dependency
Not sure if it works well with openJDK or with other OSes. Let me know how it goes!
=> Fix tools.jar on Windows

.travis.yml, pom.xml
=> Added code coverage report and integration

README.md
=> Added badges for test status and coverage

andhow-core/src/main/java/org/yarnandtail/andhow/load/std/StdEnvVarLoader.java, andhow-core/src/main/java/org/yarnandtail/andhow/load/std/StdFixedValueLoader.java, andhow-core/src/main/java/org/yarnandtail/andhow/load/std/StdJndiLoader.java, andhow-core/src/main/java/org/yarnandtail/andhow/load/std/StdMainStringArgsLoader.java, andhow-core/src/main/java/org/yarnandtail/andhow/load/std/StdPropFileOnClasspathLoader.java, andhow-core/src/main/java/org/yarnandtail/andhow/load/std/StdPropFileOnFilesystemLoader.java, andhow-core/src/main/java/org/yarnandtail/andhow/load/std/StdSysPropLoader.java
=> Issue319 Improve loader javadocs

pom.xml
=> upgraded enforcer version

andhow-core/src/main/java/org/yarnandtail/andhow/api/ValidatedValue.java
=> removed unused methods

.gitignore, README.md
* cleanup clarification
* added IntelliJ files to ignore list
=> Updated readme to include the new discussion page line

andhow-core/src/test/java/org/yarnandtail/andhow/util/AndHowUtilTest.java
=> Add tests for classExists, getClassForName, getClassInstanceForName

andhow-core/src/main/java/org/yarnandtail/andhow/api/GroupProxyBase.java, andhow-core/src/main/java/org/yarnandtail/andhow/api/GroupProxyImmutable.java, andhow-core/src/main/java/org/yarnandtail/andhow/api/GroupProxyMutable.java
=> Some constructors were unused and were removed

andhow-core/src/main/java/org/yarnandtail/andhow/api/EffectiveName.java
=> Removed unused constructor in org.yarnandtail.andhow.api.EffectiveName

andhow-core/src/main/java/org/yarnandtail/andhow/service/PropertyRegistration.java, andhow-core/src/main/java/org/yarnandtail/andhow/service/PropertyRegistrationList.java
As requested in #374. Happy Hacktoberfest! 🎃
=> Remove List constructor from PropertyRegistration

andhow-core/src/test/java/org/yarnandtail/andhow/api/PropertyTypeTest.java
=> Added JUnit tests for PropertyType enum class

andhow-core/src/test/java/org/yarnandtail/andhow/valid/LocalDateTimeValidatorTest.java
**Changes** ref #391 
---------
1. added checks for `invalidSpecificationMessage()` method
2. added checks for `getTheValueMustDescription()` method
=> cover all lines in LocalDateTimeValidator

andhow-core/src/test/java/org/yarnandtail/andhow/valid/IntValidatorTest.java
Add tests to cover null and message for #390 .
=> Add unit test IntValidator

andhow-core/src/test/java/org/yarnandtail/andhow/valid/LngValidatorTest.java
=> additional unit tests for LngValidator

andhow-core/src/main/java/org/yarnandtail/andhow/AndHow.java, andhow-core/src/main/java/org/yarnandtail/andhow/internal/ReportGenerator.java, andhow-core/src/test/java/org/yarnandtail/andhow/AndHowTest.java, andhow-testing/andhow-system-tests/src/test/java/org/yarnandtail/andhow/AndHowTest.java
=> change AndHow.isInitialize to AndHow.isInitialized

README.md
=> Issue376 readme

andhow-core/src/main/java/org/yarnandtail/andhow/api/Validator.java, andhow-core/src/main/java/org/yarnandtail/andhow/valid/DblValidator.java, andhow-core/src/main/java/org/yarnandtail/andhow/valid/IntValidator.java, andhow-core/src/main/java/org/yarnandtail/andhow/valid/LngValidator.java, andhow-core/src/main/java/org/yarnandtail/andhow/valid/LocalDateTimeValidator.java, andhow-core/src/main/java/org/yarnandtail/andhow/valid/StringValidator.java
@eeverman , Please suggest in case anything else is expected here.
=> issue-362:Returning Boolean instead of boolean

andhow-core/src/main/java/org/yarnandtail/andhow/valuetype/BolType.java, andhow-core/src/main/java/org/yarnandtail/andhow/valuetype/DblType.java, andhow-core/src/main/java/org/yarnandtail/andhow/valuetype/FlagType.java, andhow-core/src/main/java/org/yarnandtail/andhow/valuetype/IntType.java, andhow-core/src/main/java/org/yarnandtail/andhow/valuetype/LngType.java
This should resolve #430
Let me know if i've missed anything out!
=> Removing get method from type classes

andhow-core/src/test/java/org/yarnandtail/andhow/AndHowCoreTestBase.java
=> Remove duplicate and misnamed clearJNDIBeforeTest method.

andhow-core/src/main/java/org/yarnandtail/andhow/property/StrProp.java, andhow-core/src/main/java/org/yarnandtail/andhow/valid/StringValidator.java
@eeverman , please have a look, I still have to complete it.
=> Initial commit for MustMatch validation

.travis.yml, pom.xml
=> Issue481 travis build fails

appveyor.yml
=> Possible fix

andhow-annotation-processor/src/main/java/org/yarnandtail/andhow/compile/AndHowCompileProcessor.java
=> Fix Issue 484 and 485

andhow-annotation-processor/src/main/java/org/yarnandtail/andhow/compile/AndHowCompileProcessor.java, pom.xml
Also cleaned up some formatting that had gotten weird.
=> Added sonatype's staging plugin to (hopefully) make releases easier

andhow-core/src/main/java/org/yarnandtail/andhow/AndHow.java, andhow-core/src/test/java/org/yarnandtail/andhow/AndHowTest.java, andhow-core/src/test/java/org/yarnandtail/andhow/AndHowTestUtil.java, andhow-testing/andhow-simulated-app-tests/andhow-multimodule-dataprocess/andhow-default-behavior-dep1/src/test/java/com/dep1/TestInitiation.java, andhow-testing/andhow-simulated-app-tests/andhow-multimodule-dataprocess/andhow-default-behavior-dep2/src/test/java/com/dep2/TestInitiation.java, andhow-testing/andhow-simulated-app-tests/example-app-2/src/main/java/com/bigcorp/AppInitiation.java
=> Issue522 findConfig should handle reentrant requests

.gitignore, andhow-core/src/main/java/org/yarnandtail/andhow/internal/LoaderProblem.java, andhow-core/src/main/java/org/yarnandtail/andhow/load/std/StdJndiLoader.java
=> Improve jndi loader handling when JNDI is not available

.travis.yml, pom.xml
=> Issue542 shorten build time

.travis.yml, pom.xml
Fixes [#544](https://github.com/eeverman/andhow/issues/544)
* Replace Cobertura with JaCoCo in pom.xml.
* Ignore coverage report on build.
* Update travis.yml with command to generate coverage report.
* [+] Your pull request is to the *_main_* branch
* [+] Your code is up to date with the latest code from the *_main_*
* [+] You followed the guidelines in our [Developer Guide](https://sites.google.com/view/andhow/developer)?
* [+] Your code does not decrease test coverage (maybe it improves coverage!!)
* [+] If this is related to an issue, please include a link to the issue with the 'Fixes #XXX' syntax.
=> Replace Cobertura with JaCoCo.

.travis.yml
Fixes #550
* Update CodeCov's test coverage uploader.
=> Update CodeCov test coverage uploader

andhow-junit5-extensions/pom.xml, pom.xml
Fixes #566
* Replace `mockito-all` with latest `mockito-core`
=> JDK 16 support

andhow-core/src/main/java/org/yarnandtail/andhow/load/FixedValueLoader.java, andhow-core/src/main/java/org/yarnandtail/andhow/load/KeyValuePairLoader.java, andhow-core/src/main/java/org/yarnandtail/andhow/load/MapLoader.java, andhow-core/src/test/java/org/yarnandtail/andhow/load/FixedValueLoaderTest.java, andhow-core/src/test/java/org/yarnandtail/andhow/load/KeyValuePairLoaderTest.java, andhow-core/src/test/java/org/yarnandtail/andhow/load/MapLoaderTest.java
Fixes #555 
* Fix setters for loaders.
* Fix/add unit tests.
=> Fix loader setters

README.md
=> Issue588 imporved readme

andhow-core/src/main/java/org/yarnandtail/andhow/load/std/StdMainStringArgsLoader.java, andhow-core/src/test/java/org/yarnandtail/andhow/load/KeyValuePairLoaderTest.java, andhow-core/src/test/java/org/yarnandtail/andhow/load/std/StdMainStringArgsLoaderTest.java
Fixes #606 
* Override StdMainStringArgsLoader#getSpecificLoadDescription()
=> Fix StdMainStringArgsLoader description

andhow-core/src/main/java/org/yarnandtail/andhow/property/LocalDateTimeProp.java, andhow-core/src/test/java/org/yarnandtail/andhow/SimpleParams.java
=> Shorten LocalDateTimeProp#LocalDateTimeBuilder method names

andhow-core/src/main/java/org/yarnandtail/andhow/load/BaseLoader.java, andhow-core/src/main/java/org/yarnandtail/andhow/sample/JndiFileFormat.java, andhow-core/src/main/java/org/yarnandtail/andhow/sample/JndiLoaderSamplePrinter.java, andhow-core/src/main/java/org/yarnandtail/andhow/sample/PropFileLoaderSamplePrinter.java, andhow-core/src/main/java/org/yarnandtail/andhow/sample/TextBlock.java, andhow-core/src/main/java/org/yarnandtail/andhow/sample/TextLine.java, andhow-core/src/test/java/org/yarnandtail/andhow/sample/JndiLoaderSamplePrinterTest.java, andhow-core/src/test/java/org/yarnandtail/andhow/sample/PropFileLoaderSamplePrinterTest.java, andhow-core/src/test/java/org/yarnandtail/andhow/sample/TextBlockTest.java, andhow-core/src/test/java/org/yarnandtail/andhow/sample/TextLineTest.java
=> Issue615 property templates modify values

andhow-core/src/main/java/org/yarnandtail/andhow/AndHow.java, andhow-core/src/main/java/org/yarnandtail/andhow/api/StaticPropertyConfiguration.java, andhow-core/src/main/java/org/yarnandtail/andhow/internal/StaticPropertyConfigurationImmutable.java, andhow-core/src/main/java/org/yarnandtail/andhow/internal/StaticPropertyConfigurationInternal.java, andhow-core/src/main/java/org/yarnandtail/andhow/internal/StaticPropertyConfigurationMutable.java, andhow-core/src/test/java/org/yarnandtail/andhow/AndHowTest.java, andhow-testing/andhow-integration-test/src/test/java/org/yarnandtail/andhow/AndHowTest.java
=> Issue624 group proxy access should be internal only

andhow-core/src/main/java/org/yarnandtail/andhow/valid/StringValidator.java, andhow-core/src/test/java/org/yarnandtail/andhow/valid/StringValidatorTest.java
=> StringValidator.Equals checks for null entries

andhow-core/src/main/java/org/yarnandtail/andhow/AndHow.java, andhow-core/src/main/java/org/yarnandtail/andhow/internal/AndHowCore.java, andhow-core/src/main/java/org/yarnandtail/andhow/service/PropertyRegistrarLoader.java
=> Move usage of PropertyRegistrarLoader to internal only

andhow-core/src/main/java/org/yarnandtail/andhow/property/StrProp.java, andhow-core/src/main/java/org/yarnandtail/andhow/valid/StringValidator.java, andhow-core/src/test/java/org/yarnandtail/andhow/property/StrPropTest.java, andhow-core/src/test/java/org/yarnandtail/andhow/valid/StringValidatorTest.java
Fixes #610 
* Add oneOfIgnoringCase method into StrProp.StrBuilder.
* Cover with tests.
=> Add oneOfIgnoringCase method into StrProp.StrBuilder

andhow-core/src/main/java/org/yarnandtail/andhow/api/ValueType.java, andhow-core/src/main/java/org/yarnandtail/andhow/valuetype/BaseValueType.java, andhow-core/src/main/java/org/yarnandtail/andhow/valuetype/BigDecType.java, andhow-core/src/main/java/org/yarnandtail/andhow/valuetype/BolType.java, andhow-core/src/main/java/org/yarnandtail/andhow/valuetype/DblType.java, andhow-core/src/main/java/org/yarnandtail/andhow/valuetype/FlagType.java, andhow-core/src/main/java/org/yarnandtail/andhow/valuetype/IntType.java, andhow-core/src/main/java/org/yarnandtail/andhow/valuetype/LngType.java, andhow-core/src/main/java/org/yarnandtail/andhow/valuetype/LocalDateTimeType.java, andhow-core/src/main/java/org/yarnandtail/andhow/valuetype/StrType.java
=> ValueType constructors are now private to allow sublcasses

andhow-core/src/main/java/org/yarnandtail/andhow/internal/LoaderProblem.java, andhow-core/src/main/java/org/yarnandtail/andhow/internal/LoaderPropertyCoord.java, andhow-core/src/main/java/org/yarnandtail/andhow/internal/PropertyProblem.java, andhow-core/src/main/java/org/yarnandtail/andhow/internal/RequirementProblem.java, andhow-core/src/main/java/org/yarnandtail/andhow/internal/ValueProblem.java, andhow-core/src/test/java/org/yarnandtail/andhow/AndHowTest.java, andhow-core/src/test/java/org/yarnandtail/andhow/StdConfigSimulatedAppTest.java, andhow-core/src/test/java/org/yarnandtail/andhow/internal/LoaderProblemTest.java, andhow-core/src/test/java/org/yarnandtail/andhow/internal/ValueProblemTest.java, andhow-core/src/test/java/org/yarnandtail/andhow/load/std/StdJndiLoaderTest.java
* Some name refactoring (very internal classes - no impact)
* Add tests for some untested methods
* rm an unused Problem type
* Nice reduction in code and increase in testing
Fixes #684
=> Issue684 Property Problem classes should share base class

andhow-core/src/test/java/org/yarnandtail/andhow/util/AndHowLogHandlerTest.java
=> Fixes #668: Add coverage for AndHowLogHandler.

andhow-core/src/main/java/org/yarnandtail/andhow/api/ValidatedValues.java, andhow-core/src/main/java/org/yarnandtail/andhow/internal/AndHowCore.java, andhow-core/src/main/java/org/yarnandtail/andhow/internal/AndHowIllegalStateException.java, andhow-core/src/main/java/org/yarnandtail/andhow/internal/ConstructionProblem.java, andhow-core/src/test/java/org/yarnandtail/andhow/internal/AndHowCoreTest.java
=> Issue607 using an unregistered property should cause error

andhow-core/src/main/java/org/yarnandtail/andhow/sample/PropFileLoaderSamplePrinter.java, andhow-core/src/test/java/org/yarnandtail/andhow/sample/PropFileLoaderSamplePrinterTest.java
=> Remove leading comment marker on FlagProps

andhow-core/src/main/java/org/yarnandtail/andhow/property/FlagProp.java
=> javadoc change

andhow-core/src/main/java/org/yarnandtail/andhow/api/Validator.java, andhow-core/src/main/java/org/yarnandtail/andhow/api/ValueType.java, andhow-core/src/main/java/org/yarnandtail/andhow/valuetype/BaseValueType.java, andhow-core/src/test/java/org/yarnandtail/andhow/internal/LoaderProblemTest.java, andhow-core/src/test/java/org/yarnandtail/andhow/valuetype/BigDecTypeTest.java, andhow-core/src/test/java/org/yarnandtail/andhow/valuetype/DblTypeTest.java, andhow-core/src/test/java/org/yarnandtail/andhow/valuetype/IntTypeTest.java, andhow-core/src/test/java/org/yarnandtail/andhow/valuetype/LngTypeTest.java, andhow-core/src/test/java/org/yarnandtail/andhow/valuetype/LocalDateTimeTypeTest.java, andhow-testing/andhow-core-integration-test/src/test/java/org/yarnandtail/andhow/test/props/FlagPropProps.java
=> rm unused method

andhow-core/src/main/java/org/yarnandtail/andhow/api/Validator.java, andhow-core/src/main/java/org/yarnandtail/andhow/api/ValueType.java, andhow-core/src/main/java/org/yarnandtail/andhow/valid/BaseValidator.java, andhow-core/src/main/java/org/yarnandtail/andhow/valid/BigDecValidator.java, andhow-core/src/main/java/org/yarnandtail/andhow/valid/DblValidator.java, andhow-core/src/main/java/org/yarnandtail/andhow/valid/IntValidator.java, andhow-core/src/main/java/org/yarnandtail/andhow/valid/LngValidator.java, andhow-core/src/main/java/org/yarnandtail/andhow/valid/LocalDateTimeValidator.java, andhow-core/src/main/java/org/yarnandtail/andhow/valid/StringValidator.java, andhow-core/src/test/java/org/yarnandtail/andhow/valid/BigDecValidatorTest.java, andhow-core/src/test/java/org/yarnandtail/andhow/valid/DblValidatorTest.java, andhow-core/src/test/java/org/yarnandtail/andhow/valid/IntValidatorTest.java, andhow-core/src/test/java/org/yarnandtail/andhow/valid/LngValidatorTest.java, andhow-core/src/test/java/org/yarnandtail/andhow/valid/LocalDateTimeValidatorTest.java, andhow-core/src/test/java/org/yarnandtail/andhow/valid/StringValidatorTest.java
=> Validator.isValid() now throws an exception for null

andhow-core/src/main/java/org/yarnandtail/andhow/api/NamingStrategy.java, andhow-core/src/main/java/org/yarnandtail/andhow/load/std/StdJndiLoader.java, andhow-core/src/main/java/org/yarnandtail/andhow/name/CaseInsensitiveNaming.java, andhow-core/src/test/java/org/yarnandtail/andhow/name/CaseInsensitiveNamingTest.java
* Added missing test condition
Fixes #714
=> Remove unreachable code in StdJndiLoader

andhow-core/src/main/java/org/yarnandtail/andhow/AndHow.java, andhow-core/src/main/java/org/yarnandtail/andhow/internal/ConstructionProblem.java, andhow-core/src/main/java/org/yarnandtail/andhow/internal/InitializationProblem.java, andhow-core/src/main/java/org/yarnandtail/andhow/util/AndHowUtil.java, andhow-core/src/test/java/org/yarnandtail/andhow/AndHowReentrantTest.java, andhow-core/src/test/java/org/yarnandtail/andhow/AndHowTest.java, andhow-core/src/test/java/org/yarnandtail/andhow/internal/ConstructionProblemTest.java, andhow-core/src/test/java/org/yarnandtail/andhow/internal/InitializationProblemTest.java, andhow-core/src/test/java/org/yarnandtail/andhow/internal/LoaderProblemTest.java
=> Issue718 Calling setConfig() during initialization should error

.codacy.yml, .github/workflows/codacy.yml, .github/workflows/maven-ci.yaml, README.md
=> Add GitHub Actions and Codacy

.codacy.yml, .github/workflows/codacy.yml, .github/workflows/maven-ci.yaml, README.md
=> Merge CICD changes on main to branch

.github/workflows/codacy.yml, .github/workflows/maven-ci.yaml
=> Add pull-request to CICD

andhow-core/src/main/java/org/yarnandtail/andhow/api/ValueType.java, andhow-core/src/main/java/org/yarnandtail/andhow/load/util/KVP.java, andhow-core/src/main/java/org/yarnandtail/andhow/property/BolProp.java, andhow-core/src/main/java/org/yarnandtail/andhow/util/TextUtil.java, andhow-core/src/main/java/org/yarnandtail/andhow/valuetype/BolType.java, andhow-core/src/test/java/org/yarnandtail/andhow/property/BolPropTest.java, andhow-core/src/test/java/org/yarnandtail/andhow/util/TextUtilTest.java, andhow-core/src/test/java/org/yarnandtail/andhow/valuetype/BolTypeTest.java, andhow-core/src/test/java/org/yarnandtail/andhow/valuetype/FlagTypeTest.java, andhow-core/src/test/resources/org/yarnandtail/andhow/property/BolPropTest_enableNotSet.properties, andhow-core/src/test/resources/org/yarnandtail/andhow/property/BolPropTest_happyPathSetFalse.properties, andhow-core/src/test/resources/org/yarnandtail/andhow/property/BolPropTest_happyPathSetTrue.properties, andhow-testing/andhow-core-integration-test/pom.xml, andhow-testing/andhow-core-integration-test/src/test/java/org/yarnandtail/andhow/StdEnvVarLoaderIT.java, andhow-testing/andhow-core-integration-test/src/test/java/org/yarnandtail/andhow/test/bulktest/PropProblemAssertions.java, andhow-testing/andhow-core-integration-test/src/test/java/org/yarnandtail/andhow/test/bulktest/TestCoordinator.java, andhow-testing/andhow-core-integration-test/src/test/java/org/yarnandtail/andhow/test/props/FlagPropProps.java, pom.xml
=> Issue658 bol prop should have explicit false

pom.xml
=> Now allowing JDK 17 for build

README.md
=> Updated readme animation
